name: chartmann
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70045
title: WELCOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191121'
    - '#3f8c97'
    - '#aaaaaa'
    - '#d7dfab'
    - '#545256'
  brandStrength: 0
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
