name: chartmann
favicon: null
layout_spectrum: 0.5818808344192803
typography_spectrum: 0.3315008070785552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.054470314644277096
  lightness: 0.9800929317716509
  saturation: 0.9886456977110356
  rhythmicContrast: 0.3082315546926111
purpose: []
