typography_spectrum: 0.26495714602060616
color:
  brandColors:
    - '#191121'
    - '#3f8c97'
    - '#aaaaaa'
    - '#d7dfab'
    - '#545256'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2004006104543805
analytics:
  google: UA-163021-16
  facebook: null
  twitter: null
author:
  name: Christian Hartmann
  email: hello@chrishartmann.com
  url: 'http://www.chrishartmann.com'
name: chartmann
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: THE BEST ADVERTISING ISN'T ADVERTISING
description: curated stuff by @chartmann
purpose: []
