name: chartmann
favicon: null
layout_spectrum: 0.75125
typography_spectrum: 0.63367
title: CHRIS HARTMANN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363f45'
    - '#4b5f6d'
    - '#5e7c88'
    - '#24221f'
    - '#feb41c'
  brandStrength: 0.5
  lightness: 0.9800929317716509
  saturation: 1
  rhythmicContrast: 1
purpose: []
