name: chartmann
favicon: null
layout_spectrum: 0.75125
typography_spectrum: 0.63367
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272c28'
    - '#b9aaa7'
    - '#424439'
    - '#7e7867'
    - '#e9dddd'
  brandStrength: 0.5
  lightness: 0.9800929317716509
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
