layout_spectrum: 0.6266407938674092
typography_spectrum: 0.26735721132718027
color:
  brandColors:
    - '#191121'
    - '#3f8c97'
    - '#aaaaaa'
    - '#d7dfab'
    - '#545256'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: chartmann
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: THE BEST ADVERTISING ISN'T ADVERTISING
description: curated stuff by @chartmann
purpose: []
